//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAS_End_Use
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAS_End_Use()
        {
            this.CAS_End_Use_Profile = new HashSet<CAS_End_Use_Profile>();
        }
    
        public int CAS_end_use_id { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> creation_time { get; set; }
        public Nullable<System.DateTime> edit_time { get; set; }
        public string status { get; set; }
        public Nullable<int> facility_id { get; set; }
        public string end_use_name { get; set; }
        public string description { get; set; }
        public string location { get; set; }
        public string manufacturer { get; set; }
        public string model { get; set; }
        public Nullable<double> required_air_flow { get; set; }
        public Nullable<double> required_pressure { get; set; }
        public Nullable<double> measured_pressure { get; set; }
    
        public virtual CAS_Facility CAS_Facility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAS_End_Use_Profile> CAS_End_Use_Profile { get; set; }
    }
}
