//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAS_System
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAS_System()
        {
            this.CAS_Compressor = new HashSet<CAS_Compressor>();
            this.CAS_Reduce_Air_Leaks = new HashSet<CAS_Reduce_Air_Leaks>();
        }
    
        public int CAS_system_id { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> creation_time { get; set; }
        public Nullable<System.DateTime> edit_time { get; set; }
        public string status { get; set; }
        public Nullable<int> facility_id { get; set; }
        public string contact { get; set; }
        public string phone { get; set; }
        public Nullable<double> nominal_system_pressure { get; set; }
        public Nullable<double> air_flow_capacity { get; set; }
        public Nullable<double> system_elevation { get; set; }
        public Nullable<double> system_air_storage_capacity { get; set; }
        public Nullable<bool> sequencer_control { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAS_Compressor> CAS_Compressor { get; set; }
        public virtual CAS_Facility CAS_Facility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAS_Reduce_Air_Leaks> CAS_Reduce_Air_Leaks { get; set; }
    }
}
