//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAS_Compressor_Profile
    {
        public int CAS_compressor_profile_id { get; set; }
        public Nullable<int> compressor_id { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> edit_time { get; set; }
        public string status { get; set; }
        public string measure_point { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<double> air_flow { get; set; }
        public Nullable<double> temperature { get; set; }
        public Nullable<double> pressure { get; set; }
        public Nullable<double> velocity { get; set; }
    
        public virtual CAS_Compressor CAS_Compressor { get; set; }
    }
}
