//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAS_Production_Schedule
    {
        public int CAS_production_schedule_id { get; set; }
        public Nullable<int> facility_id { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> creation_time { get; set; }
        public Nullable<System.DateTime> edit_time { get; set; }
        public string status { get; set; }
        public string schedule_name { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<double> operating_hours { get; set; }
        public Nullable<double> standby_hours { get; set; }
        public Nullable<double> off_hours { get; set; }
        public Nullable<double> total_days { get; set; }
    
        public virtual CAS_Facility CAS_Facility { get; set; }
    }
}
