//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAS_Compressor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAS_Compressor()
        {
            this.CAS_Compressor_Profile = new HashSet<CAS_Compressor_Profile>();
        }
    
        public int CAS_compressor_id { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> creation_time { get; set; }
        public Nullable<System.DateTime> edit_time { get; set; }
        public string status { get; set; }
        public Nullable<int> system_id { get; set; }
        public Nullable<bool> in_service { get; set; }
        public string type { get; set; }
        public string manufacturer { get; set; }
        public Nullable<double> motor_power { get; set; }
        public Nullable<double> full_loaded_pressure { get; set; }
        public Nullable<double> full_loaded_air_flow { get; set; }
        public Nullable<double> average_temperature { get; set; }
        public Nullable<double> atmosphere_pressure { get; set; }
        public string inlet_modulation { get; set; }
        public string outlet_modulation { get; set; }
    
        public virtual CAS_System CAS_System { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAS_Compressor_Profile> CAS_Compressor_Profile { get; set; }
    }
}
