//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chiller_Equipment_Profile
    {
        public int chiller_equipment_profile_id { get; set; }
        public int equipment_id { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> creation_time { get; set; }
        public Nullable<System.DateTime> edit_time { get; set; }
        public string status { get; set; }
        public string e_status { get; set; }
        public Nullable<double> energy { get; set; }
    
        public virtual Chiller_Equipment Chiller_Equipment { get; set; }
    }
}
