//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chiller_Facility
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chiller_Facility()
        {
            this.Chillers = new HashSet<Chiller>();
            this.Chiller_Equipment = new HashSet<Chiller_Equipment>();
        }
    
        public int chiller_facility_id { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> creation_time { get; set; }
        public Nullable<System.DateTime> edit_time { get; set; }
        public string status { get; set; }
        public int company_id { get; set; }
        public string facility_name { get; set; }
        public Nullable<double> annual_energy_use { get; set; }
        public Nullable<double> flength { get; set; }
        public Nullable<double> fwidth { get; set; }
        public Nullable<double> fheight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chiller> Chillers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chiller_Equipment> Chiller_Equipment { get; set; }
        public virtual Company Company { get; set; }
    }
}
