//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginWebAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CASChillerSystemEntities : DbContext
    {
        public CASChillerSystemEntities()
            : base("name=CASChillerSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public virtual DbSet<aspnet_Users> aspnet_Users { get; set; }
        public virtual DbSet<module> modules { get; set; }
        public virtual DbSet<Transaction_Log> Transaction_Log { get; set; }
        public virtual DbSet<user_module> user_module { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<CAS_Compressor> CAS_Compressor { get; set; }
        public virtual DbSet<CAS_Compressor_Profile> CAS_Compressor_Profile { get; set; }
        public virtual DbSet<CAS_End_Use> CAS_End_Use { get; set; }
        public virtual DbSet<CAS_End_Use_Profile> CAS_End_Use_Profile { get; set; }
        public virtual DbSet<CAS_Facility> CAS_Facility { get; set; }
        public virtual DbSet<CAS_Production_Schedule> CAS_Production_Schedule { get; set; }
        public virtual DbSet<CAS_Reduce_Air_Leaks> CAS_Reduce_Air_Leaks { get; set; }
        public virtual DbSet<CAS_System> CAS_System { get; set; }
        public virtual DbSet<Chiller> Chillers { get; set; }
        public virtual DbSet<Chiller_Equipment> Chiller_Equipment { get; set; }
        public virtual DbSet<Chiller_Equipment_Profile> Chiller_Equipment_Profile { get; set; }
        public virtual DbSet<Chiller_Facility> Chiller_Facility { get; set; }
        public virtual DbSet<Chiller_Profile> Chiller_Profile { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Rate_Schedule> Rate_Schedule { get; set; }
        public virtual DbSet<Utility> Utilities { get; set; }
    }
}
