//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class module
    {
        public int module_id { get; set; }
        public string display_ID { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> creation_time { get; set; }
        public Nullable<System.DateTime> edit_time { get; set; }
        public Nullable<int> availability { get; set; }
        public string Status { get; set; }
        public string module_name { get; set; }
        public string description { get; set; }
        public string main_page { get; set; }
        public string category_column { get; set; }
    }
}
