//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate_Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rate_Schedule()
        {
            this.Utilities = new HashSet<Utility>();
        }
    
        public int rate_schedule_id { get; set; }
        public Nullable<System.DateTime> effect_date { get; set; }
        public Nullable<double> energy_rate_blk_1 { get; set; }
        public Nullable<double> energy_rate_blk_2 { get; set; }
        public Nullable<double> energy_rate_blk_3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Utility> Utilities { get; set; }
    }
}
