//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_module
    {
        public int user_module_id { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> creation_time { get; set; }
        public Nullable<System.DateTime> edit_time { get; set; }
        public Nullable<int> availability { get; set; }
        public string Status { get; set; }
        public Nullable<int> users_id { get; set; }
        public Nullable<int> Module_ID { get; set; }
        public string menu_group { get; set; }
        public Nullable<int> menu_group_sequence { get; set; }
        public Nullable<int> sequence { get; set; }
        public string module_display_name { get; set; }
        public Nullable<System.Guid> GroupFieldID { get; set; }
        public Nullable<System.Guid> DisplatFieldID { get; set; }
        public System.Guid UserModuleID { get; set; }
    }
}
